server {
  listen 80;
  server_name api.colibri-rss.com colibri-rss.com www.colibri-rss.com;

  location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

  location / {
        return 301 https://$host$request_uri;
    }
}


server {
    listen 443 ssl;
    server_name colibri-rss.com;

    ssl_certificate /etc/letsencrypt/live/colibri-rss.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/colibri-rss.com/privkey.pem;

    location / {
      resolver 127.0.0.11 valid=30s;

      # 2. Store the service name in a variable
      set $upstream_docs docs;

      # 3. Use the variable in the proxy_pass
      proxy_pass http://$upstream_docs:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_redirect off;
    }
}

server {
  listen 443 ssl;

  ssl_certificate /etc/letsencrypt/live/colibri-rss.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/colibri-rss.com/privkey.pem;

  server_name api.colibri-rss.com;

  location / {
    proxy_pass http://app:80/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
